Adcionado logger e config file
wviana/pbcli pull request #1
Opened 2018-02-12 12:44 UTC by KamenBlackRX

2018-02-12 18:42 UTC, wviana requested changes

2018-02-12 18:42 UTC, wviana commented on pbcli
> +            project "$1"
Why you've changed to `$1`?
Wouldn't it be the second param to `pbcli` as the default form will be something like:

`pbcli <command> <command_options>`

2018-02-12 18:42 UTC, wviana commented on pbcli.log
> +[INFO] 2018-02-12 10:40:52 -> Try to retrive projetos Info
This file probably shouldn't be committed. 

Maybe added into .gitignore.

I could also write the logs into /var/log as default instead of current folder.

2018-02-12 18:42 UTC, wviana commented on pbcli
> +
We could keep just one single blank line in the end of file

2018-02-12 18:42 UTC, wviana commented on pbcli
> +    --data-binary $1 '{"query":{"nao_buscar_info_detalhada":true},"opts":{"sort":{"key":"nome","order":1}},"cols":null,"id_usuario":196}' 2> /dev/null | jq  '  .data | .[] | .nome '
Remove `$1`

2018-02-12 23:10 UTC, wviana commented
Isn't there a way to change it to create a new branch instead of approving into master?
It would make easier to anyone fix this marge request.

2018-02-14 23:35 UTC, pimtel approved these changes
LGTM

2018-02-15 00:04 UTC, closed without merging